'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Loader2} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import type {Lookup,Source} from '@/lib/corner-schema';
import type {Topic} from '@/lib/stories';
export function ResearchSources({sources,html=[]}:{sources:Source[];html?:string[]}){return <details className="research-sources"><summary>Research sources</summary><ul>{sources.map((s,i)=><li key={i}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}</a></li>)}</ul>{html.map((content,i)=><iframe key={i} title={`Google Search suggestions ${i+1}`} sandbox="allow-popups allow-popups-to-escape-sandbox" referrerPolicy="no-referrer" srcDoc={`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src https: data:;"><base target="_blank">${content}`}/>)}</details>}
export default function Corner({onBack,onResult}:{onBack:()=>void;onResult:(t:Topic)=>void}){
 const [title,setTitle]=useState(''),[lookup,setLookup]=useState<Lookup|null>(null),[choice,setChoice]=useState<number|null>(null),[interest,setInterest]=useState(''),[busy,setBusy]=useState(false),[phase,setPhase]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState<boolean|null>(null),[signedIn,setSignedIn]=useState(false),[fact,setFact]=useState(0);
 const controller=useRef<AbortController|null>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;fetch('/api/corner').then(r=>r.json() as Promise<{ready:boolean;signedIn:boolean}>).then(d=>{if(alive.current){setReady(d.ready);setSignedIn(d.signedIn)}}).catch(()=>{if(alive.current)setError('We couldn’t connect. Please reload to try again.')});return()=>{alive.current=false;controller.current?.abort()}},[]);
 const seed=lookup&&choice!==null?lookup.matches[choice]:null;
 async function find(){if(busy||!title.trim())return;setBusy(true);setError('');setPhase('Finding your work.');controller.current=new AbortController();try{const r=await fetch('/api/corner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'lookup',title}),signal:controller.current.signal});const d=await r.json() as Lookup & {error?:string};if(!r.ok)throw new Error(d.error);setLookup(d);setChoice(null);setFact(0);if(!d.matches.length)setError('No confident match yet. Add the creator, year, or exact episode title.');}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Please try again.')}finally{if(alive.current)setBusy(false)}}
 async function generate(){if(!lookup||choice===null||busy)return;setBusy(true);setError('');setPhase('Finding the other two corners.');controller.current=new AbortController();let completed=false;try{const r=await fetch('/api/corner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'generate',id:lookup.id,choice,interest}),signal:controller.current.signal});if(!r.ok){const d=await r.json() as {error:string};throw new Error(d.error)}if(r.headers.get('Content-Type')?.includes('application/json')){const d=await r.json() as {topic:Topic};completed=true;onResult(d.topic);return}const reader=r.body?.getReader();if(!reader)throw new Error('The connection was interrupted. Please try again.');const decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==='status')setPhase(event.text);if(event.type==='error')throw new Error(event.error);if(event.type==='result'){completed=true;onResult(event.topic);return}}if(done)break}if(!completed)throw new Error('The connection was interrupted. Try again to recover your triangle.');}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Please try again.')}finally{if(alive.current)setBusy(false)}}
 return <main className="corner-page" id="main"><button className="back-shelf" onClick={onBack}><ArrowLeft size={16}/> Back</button><div className="corner-layout"><div className="corner-heading"><p className="eyebrow">YOUR FIRST CORNER</p><h1>{busy&&seed?'A world is taking shape.':seed?'What grabbed you?':'What’s the title?'}</h1><p>{busy&&seed?'We’re researching the connections. A few discoveries to explore while we work.':seed?'The setting? A character? An idea you can’t shake? Tell us what to follow—or leave it open.':'A book you loved. A film that stayed with you. A podcast episode you can’t stop thinking about.'}</p></div>
 {ready===true&&!signedIn?<div className="corner-notice"><h2>Make it yours.</h2><p>Reload to start your private browser session.</p><button className="solid-button" onClick={()=>location.reload()}>Reload <ArrowRight size={18}/></button></div>:<div className="corner-form">{ready===false&&<div className="corner-notice"><h2>Coming soon.</h2><p>Custom triangles aren’t available yet. You can still explore our curated topics.</p></div>}
 {!seed&&<form onSubmit={e=>{e.preventDefault();find()}}><label htmlFor="corner-title">Title of the work</label><Input id="corner-title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. The Emerald Mile" maxLength={240} disabled={busy}/><p className="field-note">For a podcast, use the episode title. Add a creator if the title is common.</p><button className="solid-button" disabled={busy||ready!==true||!title.trim()}>{busy?<Loader2 className="spin" size={18}/>:<ArrowRight size={18}/>} {busy?'Finding your work…':'Find my work'}</button></form>}
 {lookup&&!seed&&!busy&&lookup.matches.length>0&&<section className="corner-matches"><h2>Which one did you mean?</h2>{lookup.matches.map((m,i)=><button key={i} onClick={()=>{setChoice(i);setFact(0)}}><span className="eyebrow">{m.format} · {m.year}</span><h3>{m.title}</h3><p>{m.creator}</p><p>{m.description}</p><span className="match-confirm">This is the one <Check size={16}/></span></button>)}<ResearchSources sources={lookup.sources} html={lookup.searchHtml}/></section>}
 {seed&&!busy&&<><div className="confirmed-work"><span className="eyebrow">{seed.format} · {seed.year}</span><h2>{seed.title}</h2><p>{seed.creator}</p><button onClick={()=>setChoice(null)}>Choose a different work</button></div><form onSubmit={e=>{e.preventDefault();generate()}}><label htmlFor="corner-interest">What grabbed you? <span>(optional)</span></label><Textarea id="corner-interest" value={interest} onChange={e=>setInterest(e.target.value)} maxLength={600} placeholder="I came for the whitewater, but stayed for the obsession." rows={4}/><p className="field-note">Your work stays. We’ll find the other two angles and a bonus.</p><button className="solid-button">Build my threeangle <ArrowRight size={18}/></button></form></>}
 {busy&&seed&&<section className="corner-wait"><svg className="building-triangle" viewBox="0 0 240 220" aria-hidden="true"><path d="M120 20 120 140 20 195Z"/><path d="M120 20 220 195 120 140Z"/><path d="M20 195 120 140 220 195Z"/></svg><p role="status"><Loader2 className="spin" size={16}/>{phase}</p>{seed.facts.length>0&&<div className="corner-fact"><span className="eyebrow">WHILE WE CONNECT THE DOTS</span><p>{seed.facts[fact%seed.facts.length].text}</p><a href={lookup!.sources[seed.facts[fact%seed.facts.length].source].url} target="_blank" rel="noopener noreferrer">Read the source ↗</a>{seed.facts.length>1&&<button onClick={()=>setFact(f=>f+1)}>Another discovery <ArrowRight size={16}/></button>}</div>}<ResearchSources sources={lookup!.sources} html={lookup!.searchHtml}/><p className="field-note">This may take a couple of minutes. Keep this page open.</p></section>}
 </div>}{error&&<p className="corner-error" role="alert">{error}</p>}</div></main>
}
