'use client';
import {useState,useEffect,useRef,useCallback,type CSSProperties} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,Shuffle,Plus,Check,PackageOpen,X,RotateCcw,Loader2} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import Opening from './opening';
import Helix from './helix';
import Corner,{ResearchSources} from './corner';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {topics,workUrl,type Topic} from '@/lib/stories';
const labels=['The hook','Read','Watch','Listen','The shift','One more thing'];
function Mark({angle=0,className=''}:{angle?:number;className?:string}){return <svg className={'mark '+className} viewBox="0 0 72 68" aria-hidden="true"><g style={{transform:`rotate(${angle*120}deg)`,transformOrigin:'36px 36px'}}><path d="M36 6 65 57H7Z M36 6v32L7 57m29-19 29 19" fill="none" stroke="currentColor" strokeWidth="4.5" strokeLinejoin="round"/><circle cx="36" cy="38" r="5.5" fill="currentColor"/></g></svg>}
function Art({topic,className=''}:{topic:Topic;className?:string}){const i=topic.pilotIndex%6;if(topic.pilotIndex>=12)return <div aria-hidden="true" className={'world-art typography-art '+className} style={{'--world':topic.color} as CSSProperties}><span>{topic.seedTitle?'3A':String(topic.pilotIndex+1).padStart(2,'0')}</span></div>;return <div aria-hidden="true" className={'world-art '+className} style={{backgroundImage:`url(/worlds-${topic.pilotIndex<6?1:2}.jpg)`,backgroundPosition:`${i%3*50}% ${i<3?0:100}%`}}/>}
function Words({text}:{text:string}){return <>{text.split(' ').map((word,i)=><span className="word" key={i} style={{'--delay':`${i*35}ms`} as CSSProperties}>{word}{' '}</span>)}</>}
export default function Experience({startBrowsing=false}:{startBrowsing?:boolean}){
 const [mode,setMode]=useState<'choose'|'browse'|'corner'>(startBrowsing?'browse':'choose'),[customTopics,setCustomTopics]=useState<Topic[]>([]);
 const [menuIndex,setMenuIndex]=useState(0),[side,setSide]=useState(0),[shuffleCount,setShuffleCount]=useState(0),[selected,setSelected]=useState<Topic|null>(null),[stage,setStage]=useState(0),[angle,setAngle]=useState(0),[crateOpen,setCrateOpen]=useState(false),[intro,setIntro]=useState(!startBrowsing),[saved,setSaved]=useState<string[]>([]),[loading,setLoading]=useState(true),[crateError,setCrateError]=useState(''),[needsSignIn,setNeedsSignIn]=useState(false),[pending,setPending]=useState<string[]>([]);
 const stageRef=useRef<HTMLDivElement>(null),touch=useRef<{x:number;y:number}|null>(null);
 const shelf=topics.slice(side*6,side*6+6);
 const readHash=useCallback(()=>{if(new URLSearchParams(location.search).get('corner')){setIntro(false);setMode('corner');history.replaceState(null,'',location.pathname+location.hash)}const parts=window.location.hash.slice(1).split('/');const t=[...topics,...customTopics].find(t=>t.id===parts[0]);setSelected(t||null);if(t)setIntro(false);if(!t&&/^custom-[0-9a-f-]{36}$/.test(parts[0])){setIntro(false);setMode('corner');fetch('/api/corner?id='+encodeURIComponent(parts[0].slice(7))).then(r=>r.json() as Promise<{topic?:Topic;error?:string}>).then(d=>{if(d.topic&&location.hash.slice(1).split('/')[0]===parts[0]){const restored=d.topic;setCustomTopics(prev=>[...prev.filter(x=>x.id!==restored.id),restored]);}else if(d.error)toast.error(d.error)}).catch(()=>toast.error('Your custom triangle could not be loaded.'));}setStage(t?Math.max(0,Math.min(5,Number(parts[1])||0)):0);setAngle(0)},[customTopics]);
 useEffect(()=>{readHash();window.addEventListener('popstate',readHash);window.addEventListener('hashchange',readHash);return()=>{window.removeEventListener('popstate',readHash);window.removeEventListener('hashchange',readHash)}},[readHash]);
 const loadCrate=useCallback(async()=>{setLoading(true);setCrateError('');setNeedsSignIn(false);try{const r=await fetch('/api/crate',{cache:'no-store'});const d=await r.json() as {error?:string;items:{topicId:string;topic?:Topic|null}[]};if(!r.ok){setNeedsSignIn(r.status===401);throw new Error(d.error||'Your crate could not be opened.')}setSaved(d.items.map((x:{topicId:string})=>x.topicId));setCustomTopics(prev=>{const incoming=d.items.flatMap(x=>x.topic?[x.topic]:[]);return [...prev.filter(t=>!incoming.some(n=>n.id===t.id)),...incoming]});}catch(e){setCrateError(e instanceof Error?e.message:'Your crate could not be opened.')}finally{setLoading(false)}},[]);
 useEffect(()=>{loadCrate()},[loadCrate]);
 function open(t:Topic,s=0){setMode(t.seedTitle?'corner':'browse');if(!t.seedTitle)setMenuIndex(t.pilotIndex);setSelected(t);setStage(s);setAngle(0);setCrateOpen(false);history.pushState(null,'',`#${t.id}/${s}`);window.scrollTo(0,0)}
 function close(){const id=selected?.id;setSelected(null);history.pushState(null,'',location.pathname);window.scrollTo(0,0);setTimeout(()=>document.querySelector<HTMLButtonElement>('.helix-stage')?.focus({preventScroll:true}),0)}
 const go=useCallback((s:number)=>{if(!selected)return;const v=Math.max(0,Math.min(5,s));setStage(v);setAngle(0);history.replaceState(null,'',`#${selected.id}/${v}`)},[selected]);
 useEffect(()=>{if(selected){stageRef.current?.scrollTo(0,0);stageRef.current?.focus({preventScroll:true})}document.title=selected?`${selected.name} / threeangle`:'threeangle / Find your next fascination.'},[selected,stage]);
 useEffect(()=>{function key(e:KeyboardEvent){if(!selected||crateOpen||intro||e.metaKey||e.ctrlKey||e.altKey)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='ArrowRight'){e.preventDefault();go(stage+1)}else if(e.key==='ArrowLeft'){e.preventDefault();go(stage-1)}else if(e.key==='Escape'){e.preventDefault();close()}else if(e.key===' '&&!target.closest('button,a')){e.preventDefault();go(stage+1)}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[selected,stage,crateOpen,intro,go]);
 async function save(t:Topic,remove=false){if(pending.includes(t.id)||loading)return;if(needsSignIn){setCrateOpen(true);return}if(crateError){setCrateOpen(true);return}setPending(p=>[...p,t.id]);try{const r=await fetch('/api/crate',{method:remove?'DELETE':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({topicId:t.id})});const d=await r.json() as {error?:string};if(!r.ok){if(r.status===401){setNeedsSignIn(true);setCrateError(d.error||"Please sign in to save your finds.");setCrateOpen(true)}throw new Error(d.error||'That change could not be saved.')}setSaved(prev=>remove?prev.filter(id=>id!==t.id):[t.id,...prev.filter(id=>id!==t.id)]);toast.success(remove?'Removed from your crate.':`${t.name} In the crate.`,{description:remove?'You can add it again whenever you like.':'The whole triangle is saved for later.'});}catch(e){toast.error(e instanceof Error?e.message:'Could not save. Please try again.')}finally{setPending(p=>p.filter(id=>id!==t.id))}}
 function SaveButton({t,compact=false}:{t:Topic;compact?:boolean}){const isSaved=saved.includes(t.id),busy=pending.includes(t.id)||loading;return <button className={'save-button '+(isSaved?'is-saved ':'')+(compact?'compact':'')} onClick={()=>isSaved?setCrateOpen(true):save(t)} disabled={busy} aria-label={busy?'Loading crate':isSaved?'Open your crate':`Save ${t.name} to your crate`}>{busy?<Loader2 className="spin" size={17}/>:isSaved?<Check size={17}/>:<Plus size={17}/>}<span>{isSaved?'In your crate':'Keep this world'}</span></button>}
 if(intro)return <Opening onEnter={()=>{setIntro(false);setMode('choose');window.scrollTo(0,0)}}/>;
 return <div className={'experience '+(selected?'in-world':'on-shelf')} style={selected?{'--world':selected.color} as CSSProperties:undefined}>
 <a href="#main" className="skip-link">Skip to discoveries</a>
 <header className="site-header"><button className="wordmark" onClick={()=>{if(selected)close();setMode('choose');window.scrollTo(0,0)}} aria-label="threeangle home"><Mark angle={selected?stage:shuffleCount}/><span>threeangle<sup>/02</sup></span></button><div className="header-center">{selected?<span>{selected.kicker}</span>:<span>CULTURE. ALL ANGLES.</span>}</div><nav><button className="idea-button" onClick={()=>setIntro(true)}>How it works</button><button className="crate-trigger" onClick={()=>setCrateOpen(true)}><PackageOpen size={18}/><span>Your crate</span><b>{loading?'·':saved.length}</b></button></nav></header>
 {!selected?mode==='choose'?<main id="main" className="entry-choice"><p className="eyebrow">TWO WAYS IN</p><h1>Where do we start?</h1><div className="entry-options"><button onClick={()=>setMode('browse')}><span className="entry-number">01</span><h2>Pick a topic.</h2><p>Explore 24 worlds we’ve curated. Three works and a bonus in each.</p><ArrowRight size={26}/></button><button onClick={()=>setMode('corner')}><span className="entry-number">02</span><h2>I have a title.</h2><p>Bring a work you love. We’ll build a custom threeangle around it.</p><ArrowRight size={26}/></button></div></main>:mode==='corner'?<Corner onBack={()=>setMode('choose')} onResult={t=>{setCustomTopics(prev=>[...prev.filter(x=>x.id!==t.id),t]);open(t)}}/>:<Helix onOpen={open} initialIndex={menuIndex}/>:<main id="main" className={'world stage-'+stage}>
 <div className="world-bar"><button className="back-shelf" onClick={close}><ArrowLeft size={16}/> {selected.seedTitle?'Back to your corner':'Back to topics'}</button><span className="world-name">{selected.name}</span><SaveButton t={selected}/></div>
 <div className="scene-scroll" ref={stageRef} tabIndex={-1} onTouchStart={e=>{if((e.target as HTMLElement).closest('button,a'))return;touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;touch.current=null;if(Math.abs(dx)>70&&Math.abs(dy)<70)go(stage+(dx<0?1:-1))}}>
 <div className={'scene scene-'+stage} key={selected.id+'-'+stage}>
 {stage===0&&<><div className="hook-art"><Art topic={selected}/></div><div className="hook-shade"/><div className="hook-content"><p className="eyebrow">HERE’S YOUR WAY IN.</p><h1><Words text={selected.hook}/></h1><p className="hook-intro">{selected.intro}</p>{selected.seedTitle&&<p className="custom-origin">Built around {selected.seedTitle} · Curated with AI</p>}<div className="hook-promise"><Mark/><span>Three great works.<br/>One very good rabbit hole.</span></div></div><span className="scene-stamp">3A / {selected.seedTitle?'YOURS':String(selected.pilotIndex+1).padStart(2,'0')}</span></>}
 {stage>0&&stage<4&&<><div className="pitch-left"><span className="eyebrow">ANGLE 0{stage} / {labels[stage].toUpperCase()}</span><h1><Words text={selected.heads[stage-1]}/></h1><p className="pitch-copy">{selected.works[stage-1].pitch}</p><div className="bridge"><span>THE NEXT TURN</span><p>{selected.bridges[stage-1]}</p></div></div><div className="work-panel"><div className="work-panel-art"><Art topic={selected}/></div><div className="work-panel-shade"/><div className="work-panel-top"><span>{selected.works[stage-1].format.toUpperCase()}</span><span>0{stage} / 03</span></div><div className="angle-emblem"><svg viewBox="0 0 240 220" aria-hidden="true"><path d="M120 15 224 195H16Z" fill="none" stroke="currentColor" strokeWidth="2"/><path d={stage===1?'M16 195 120 15':stage===2?'M120 15 224 195':'M224 195H16'} fill="none" stroke="currentColor" strokeWidth="9"/><circle cx={stage===1?120:stage===2?224:16} cy={stage===1?15:195} r="9" fill="currentColor"/></svg></div><div className="work-info"><h2>{selected.works[stage-1].title}</h2><p>{selected.works[stage-1].creator}</p><a href={workUrl(selected.works[stage-1])} target="_blank" rel="noopener noreferrer">{selected.works[stage-1].url?'Explore the work':'Find the work'}<ArrowUpRight size={21}/><span className="sr-only"> (opens in new tab)</span></a></div></div></>}
 {stage===4&&<div className="payoff"><div className="payoff-heading"><p className="eyebrow">THREE ANGLES. NOW THE PICTURE CHANGES.</p><h1><Words text={selected.shift}/></h1><p className="payoff-copy">{selected.payoff}</p></div>{selected.sources&&<ResearchSources sources={selected.sources} html={selected.searchHtml}/>}<div className="triangle-works">{selected.works.slice(0,3).map((w,i)=><div className={'mini-work '+(angle===i?'lit':'')} key={w.title}><span className="eyebrow">0{i+1} / {labels[i+1].toUpperCase()}</span><h2>{w.title}</h2><p>{w.creator}</p><a href={workUrl(w)} target="_blank" rel="noopener noreferrer">{w.url?'Explore':'Find it'} <ArrowUpRight size={16}/><span className="sr-only"> (opens in new tab)</span></a></div>)}</div><div className="perspective"><div><h3>{selected.question}</h3><div className="perspective-buttons" role="group" aria-label="Explore three perspectives">{selected.angles.map((a,i)=><button key={a} aria-pressed={angle===i} className={angle===i?'selected':''} onClick={()=>setAngle(i)}>{a}</button>)}</div></div><p key={angle} className="angle-answer" aria-live="polite">{selected.answers[angle]}</p></div></div>}
 {stage===5&&<><div className="bonus-left"><span className="eyebrow">+ THE FOURTH ANGLE</span><h1><Words text={selected.bonus}/></h1><p className="bonus-intro">For when you’re not ready to leave this world.</p><div className="bonus-work"><span className="eyebrow">{selected.works[3].format.toUpperCase()}</span><h2>{selected.works[3].title}</h2><p className="bonus-creator">{selected.works[3].creator}</p><p>{selected.works[3].pitch}</p><a href={workUrl(selected.works[3])} target="_blank" rel="noopener noreferrer">Follow this tangent <ArrowUpRight size={18}/><span className="sr-only"> (opens in new tab)</span></a></div></div><div className="bonus-right"><Art topic={selected}/><div className="bonus-shade"/><Mark angle={stage}/><div className="bonus-keep"><p>This one’s a keeper.</p><SaveButton t={selected}/><span>Save the whole triangle.<br/>Come back when the mood finds you.</span></div></div></>}
 </div></div>
 <div className="transport"><div className="transport-progress"><span className="step-count">0{stage+1}<small>/06</small></span><div className="step-buttons">{labels.map((l,i)=><button key={l} onClick={()=>go(i)} className={i===stage?'current':i<stage?'past':''} aria-label={`Step ${i+1}: ${l}`} aria-current={i===stage?'step':undefined}><i/><span>{l}</span></button>)}</div></div><div className="transport-actions">{stage>0&&<button className="previous" aria-label="Previous angle" onClick={()=>go(stage-1)}><ArrowLeft size={19}/></button>}{stage===0&&<button className="skip-pitch" onClick={()=>go(4)}>Just the picks</button>}<button className="next-scene" onClick={()=>stage===5?close():go(stage+1)}><span>{['I’m listening','Show me the connection','And the third angle?','Put it together','One more thing…','Back to topics'][stage]}</span><ArrowRight size={19}/></button></div></div>
 </main>}
 <Sheet open={crateOpen} onOpenChange={setCrateOpen}><SheetContent className="crate-sheet"><div className="crate-heading"><span className="eyebrow">GOOD FINDS, KEPT CLOSE.</span><SheetTitle>Your crate.</SheetTitle><SheetDescription>The worlds you want to come back to.</SheetDescription></div>{loading?<div className="crate-state"><Loader2 className="spin"/><p>Opening your crate…</p></div>:crateError?<div className="crate-state"><PackageOpen size={42}/><p>{crateError}</p>{needsSignIn?<button className="solid-button" onClick={()=>location.reload()}>Reconnect your crate</button>:<button className="solid-button" onClick={loadCrate}>Try again</button>}</div>:saved.length===0?<div className="crate-state empty-crate"><Mark/><h3>Something will<br/>stay with you.</h3><p>When a world grabs you, tap “Keep this world.” Its three works—and the bonus—will be waiting here.</p><button className="solid-button" onClick={()=>setCrateOpen(false)}>Back to the good stuff <ArrowRight size={18}/></button></div>:<div className="crate-items">{saved.map(id=>[...topics,...customTopics].find(t=>t.id===id)).filter((t):t is Topic=>!!t).map(t=><article className="crate-item" key={t.id} style={{'--world':t.color} as CSSProperties}><button className="crate-art" aria-label={`Replay ${t.name}`} onClick={()=>open(t)}><Art topic={t}/></button><div><span className="eyebrow">{t.kicker.split(' / ')[0]}</span><h3>{t.name}</h3><div className="crate-item-actions"><button onClick={()=>open(t,0)}><RotateCcw size={13}/> Replay</button><button onClick={()=>open(t,4)}>The picks <ArrowUpRight size={14}/></button></div></div><button className="remove-item" disabled={pending.includes(t.id)} aria-label={`Remove ${t.name} from crate`} onClick={()=>save(t,true)}>{pending.includes(t.id)?<Loader2 size={16} className="spin"/>:<X size={16}/>}</button></article>)}</div>}<p className="crate-footnote">Your finds are saved for this browser. Clearing cookies removes access.</p></SheetContent></Sheet>

 <Toaster position="bottom-right" theme="dark" richColors/>
 </div>
}
