'use client';
import {useState,useRef,useEffect,type CSSProperties} from 'react';
import {ArrowUp,ArrowDown,ArrowRight,Pause,Play,Shuffle} from 'lucide-react';
import {topics,type Topic} from '@/lib/stories';
const wrap=(n:number)=>((n%topics.length)+topics.length)%topics.length;
export default function Helix({onOpen,initialIndex=0}:{onOpen:(t:Topic)=>void;initialIndex?:number}){
 const [position,setPosition]=useState(initialIndex),[auto,setAuto]=useState(false),[reduced,setReduced]=useState(false);
 const target=useRef(initialIndex),current=useRef(initialIndex),drag=useRef<{y:number;p:number;moved:boolean}|null>(null),stage=useRef<HTMLDivElement>(null),last=useRef(0);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(q.matches);sync();q.addEventListener('change',sync);return()=>q.removeEventListener('change',sync)},[]);
 useEffect(()=>{let frame=0,prev=performance.now();function tick(now:number){if(auto&&!reduced&&!document.hidden&&now-last.current>2000&&!drag.current)target.current+=(now-prev)*.00012;prev=now;current.current=reduced?target.current:current.current+(target.current-current.current)*.085;if(Math.abs(target.current-current.current)<.0001)current.current=target.current;setPosition(current.current);frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[auto,reduced]);
 const move=(n:number)=>{target.current=Math.round(target.current)+n;last.current=performance.now()};
 useEffect(()=>{const el=stage.current;if(!el)return;const wheel=(e:WheelEvent)=>{if(e.ctrlKey)return;e.preventDefault();target.current+=Math.max(-110,Math.min(110,e.deltaY))*.005;last.current=performance.now()};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[]);
 const active=wrap(Math.round(position)),t=topics[active];
 return <main id="main" className="helix-menu">
 <div className="helix-layout"><div className="helix-stage" ref={stage} tabIndex={0} role="region" aria-label="Topic spiral. Use up and down arrows to browse, Enter to open." onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(['ArrowDown','ArrowRight'].includes(e.key)){e.preventDefault();move(1)}if(['ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();move(-1)}if(e.key==='Enter')onOpen(t);if(e.key==='Home'){e.preventDefault();target.current=0}if(e.key==='End'){e.preventDefault();target.current=topics.length-1}}}
 onPointerDown={e=>{if(e.button!==0)return;drag.current={y:e.clientY,p:target.current,moved:false};last.current=performance.now()}}
 onPointerMove={e=>{if(!drag.current)return;const delta=(drag.current.y-e.clientY)/145;if(Math.abs(delta)>.035){drag.current.moved=true;e.currentTarget.setPointerCapture(e.pointerId)}target.current=drag.current.p+delta}}
 onPointerUp={e=>{if(drag.current?.moved){target.current=Math.round(target.current);setTimeout(()=>{drag.current=null},0)}else drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>{drag.current=null;target.current=Math.round(target.current)}}>
 <div className="helix-space">{topics.map((topic,i)=>{let d=wrap(i-position);if(d>topics.length/2)d-=topics.length;const visible=Math.abs(d)<5.3,a=d*.78,z=Math.cos(a)*150,x=Math.sin(a)*235,y=d*116;return <button key={topic.id} className={'helix-card '+(i===active?'is-active':'')} tabIndex={-1} aria-hidden={!visible} aria-label={`Open ${topic.name}`} onClick={()=>{if(drag.current?.moved)return;if(i===active)onOpen(topic);else{target.current=position+d;last.current=performance.now()}}} style={{'--world':topic.color,transform:`translate3d(${x}px,${y}px,${z}px) rotateY(${-Math.sin(a)*45}deg)`,opacity:visible?Math.max(.15,1-Math.abs(d)*.17):0,visibility:visible?'visible':'hidden',zIndex:Math.round(z+200),pointerEvents:visible?'auto':'none'} as CSSProperties}>
 <div className={"helix-art "+(topic.pilotIndex>=12?"typography-art":"")} style={{backgroundImage:topic.pilotIndex<12?`url(/worlds-${Math.floor(topic.pilotIndex/6)+1}.jpg)`:undefined,backgroundPosition:`${topic.pilotIndex%3*50}% ${topic.pilotIndex%6<3?0:100}%`}}>{topic.pilotIndex>=12&&<span>{String(topic.pilotIndex+1).padStart(2,'0')}</span>}</div><div className="helix-shade"/><span className="helix-card-number">{String(i+1).padStart(2,'0')} / 24</span><div className="helix-card-copy"><span>{topic.kicker.split(' / ')[0]}</span><h2>{topic.name}</h2></div></button>})}</div>
 <div className="helix-hint">SCROLL OR DRAG TO BROWSE</div></div>
 <aside className="helix-selection"><div className="helix-navigation"><button onClick={()=>move(-1)} aria-label="Previous topic"><ArrowUp size={20}/></button><span aria-live="polite">{String(active+1).padStart(2,'0')} <small>/ 24</small></span><button onClick={()=>move(1)} aria-label="Next topic"><ArrowDown size={20}/></button></div><div key={t.id} className="helix-selected-copy"><p className="eyebrow" style={{color:t.color}}>{t.kicker}</p><p className="helix-teaser">{t.intro}</p><button className="solid-button helix-open" onClick={()=>onOpen(t)}>Explore this topic <ArrowRight size={20}/></button><span className="helix-promise">Read · Watch · Listen · Bonus</span></div><div className="helix-options"><button onClick={()=>move(1+Math.floor(Math.random()*(topics.length-1)))}><Shuffle size={16}/> Surprise me</button>{!reduced&&<button aria-pressed={auto} onClick={()=>setAuto(v=>!v)}>{auto?<Pause size={16}/>:<Play size={16}/>} {auto?'Pause rotation':'Auto-rotate'}</button>}</div></aside></div></main>
}
